const ACCOUNT = {
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILD: 'LOG_IN_FAILD',
  LOG_IN_FETCH: 'LOG_IN_FETCH',
};
const ACCOUNT_WORDS = {
  FETCH: "ACCOUNT_WORDS_FETCH",
  FETCH_ERROR: "ACCOUNT_WORDS_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_WORDS_FETCH_SUCCESS",
};
export {ACCOUNT,ACCOUNT_WORDS};
